# Distributed-Motion-S3 DMS3Libs Component Configuration File
# 1.4.2

[SysCommands]

  # SysCommands provide a location mapping of required system commands used by various DMS3
  # components
  #
  APLAY = "/usr/bin/aplay"
  BASH = "/usr/bin/bash"
  CAT = "/usr/bin/cat"
  ENV = "/usr/bin/env"
  GREP = "/usr/bin/grep"
  IP = "/usr/sbin/ip"
  PGREP = "/usr/bin/pgrep"
  PING = "/usr/bin/ping"
  PKILL = "/usr/bin/pkill"

  # TODO need to update documentation to detail Motion/MotionPlus configuration

  # the Motion application is currently used for motion detection and is configured differently
  # based on the version of Motion (or MotionPlus) installed on the client, and the client OS in
  # use
  #
  # When in doubt, consult the Motion documentation: https://motion-project.github.io/
  #
  # As an example, Motion 4.7.x running on a Raspberry Pi with the Bookworm (or later) OS requires
  # special configuration and the command to start Motion is "libcamerify motion"
  #
  # MOTION = "/usr/bin/libcamerify motion"
  # 
  # In the configuration below, the MotionPlus application is used, and in a recent release
  # (0.2.2), the command to include its configuration file is required when running the dms3client
  # as a system service
  #
  # MOTION = "/usr/local/bin/motionplus -c /usr/local/etc/motionplus/motionplus.conf"
  #
  # Alternatively, in the above case when running a system service, the dms3client.service file
  # can instead be edited to specify the MotionPlus configuration folder:
  #
  # ...
  # WorkingDirectory=/usr/local/etc/motionplus
  # ...
  #
  # In this latter case, the following command is used (no need to specify the configuration
  # folder):
  #
  MOTION = "/usr/local/bin/motionplus"
