# Distributed-Motion-S3 (DMS3) BUILD configuration file
# TOML 1.0.0

[Clients]

   [Clients.0]
      User = "pi"
      DeviceName = "picam-alpha.local"
      SSHPassword = ""        # using SSH certificate
      RemoteAdminPassword = "PASSWORD"
      Port = 22
      Platform = "linuxArm7"

   [Clients.1]
      User = "pi"
      DeviceName = "picam-beta.local"
      SSHPassword = ""      # using SSH certificate
      RemoteAdminPassword = "PASSWORD"
      Port = 22
      Platform = "linuxArm7"

   [Clients.2]
      User = "pi"
      DeviceName = "picam-gamma.local"
      SSHPassword = ""      # using SSH certificate
      RemoteAdminPassword = "PASSWORD"
      Port = 22
      Platform = "linuxArm6"

   [Clients.3]
      User = "richbl"
      DeviceName = "main.local"
      SSHPassword = ""      # using SSH certificate
      RemoteAdminPassword = "PASSWORD"
      Port = 22
      Platform = "linuxAMD64"

[Servers]

   [Servers.0]
      User = "richbl"
      DeviceName = "main.local"
      SSHPassword = ""      # using SSH certificate
      RemoteAdminPassword = "PASSWORD"
      Port = 22
      Platform = "linuxAMD64"
