# Distributed-Motion-S3 DMS3Libs Component Configuration File
# 1.4.4

[SysCommands]

  # SysCommands provide a location mapping of required system commands used by various DMS3
  # components
  #
  APLAY = "/usr/bin/aplay"
  BASH = "/usr/bin/bash"
  CAT = "/usr/bin/cat"
  ENV = "/usr/bin/env"
  GREP = "/usr/bin/grep"
  IP = "/usr/sbin/ip"
  PGREP = "/usr/bin/pgrep"
  PING = "/usr/bin/ping"
  PKILL = "/usr/bin/pkill"

  # the Motion application--currently used as the default for DMS3 motion detection--is configured 
  # differently based on the version of Motion installed on the client and the client OS in use
  #
  # When in doubt, consult the Motion project documentation: https://motion-project.github.io/
  #
  # -----------------
  #
  # For Motion 4.7.x running on a Raspberry Pi with the Bookworm (or later) OS release, the
  # following command assignment should be used:
  #
  # MOTION = "/usr/bin/libcamerify motion"
  #
  # -----------------
  #
  # For future versions of Motion (5.x.x is the next planned release), the following
  # command assignment should be used (the location of the motion binary with the -c switch used
  # to specify the configuration file location):
  #
  # MOTION = "/usr/local/bin/motion -c /usr/local/etc/motion/motion.conf"
  #
  # -----------------
  #
  # Alternatively, when choosing to run DMS3 client(s) as a systemd service, the dms3client.service
  # file (included in this project) can be edited to specify the location of the motion.conf 
  # configuration file:
  #
  #   ...
  #   [Service]
  #   WorkingDirectory=/usr/local/etc/motion
  #   ...
  #
  # In this case--when running DMS3 client(s) as a systemd service--there's no need to specify the
  # configuration file location, so the following command assignment is used:
  #
  MOTION = "/usr/local/bin/motion"
