# Distributed-Motion-S3 (DMS3) SERVER configuration file
# TOML 1.0.0

[Server]
  # Port is the port on which to run the motion server
  Port = 49300

  # CheckInterval is the interval (in seconds) between local checks for change to motion_state
  CheckInterval = 15

  # Enables (true) or disables (false) the DMS3 dashboard running over HTTP on this server
  EnableDashboard = true

[Audio]
  # Enables (true) or disables (false) the play-back of audio on motion detector application 
  # start/stop
  #
  Enable = true

  # PlayMotionStart is the audio file played when the motion detector application is activated
  # By default, the value is "" (empty string), which gets set to the path of the release /media
  # folder and filename (e.g., /etc/distributed-motion-s3/dms3server/media/motion_start.wav)
  # Any other filepath/filename will be used if valid, else set to local development folder
  #
  # Ignored if Audio.Enable == false
  #
  PlayMotionStart = ""

  # PlayMotionStart is the audio file played when the motion detector application is activated
  # By default, the value is "" (empty string), which gets set to the path of the release /media
  # folder and filename (e.g., /etc/distributed-motion-s3/dms3server/media/motion_stop.wav)
  # Any other filepath/filename will be used if valid, else set to local development folder
  #
  # Ignored if Audio.Enable == false
  #
  PlayMotionStop = ""

[AlwaysOn]
  # Enables (true) or disables (false) motion detector application based on time-of-day
  Enable = true

  # TimeRange is the start and end times (24-hour format) for motion to always be enabled,
  # regardless of absence/existence of user proxy device(s) on the LAN
  #
  # Ignored if AlwaysOn.Enable == false
  #
  TimeRange = ["2300", "0400"]

[UserProxy]
  # IPBase is the first three address octets defining the LAN (e.g., 10.10.10.) where user
  # proxies (devices representing users on the network, such as a smartphone) will
  # be scanned for to determine when motion should be run
  #
  IPBase = "10.10.10."

  # IPRange is the fourth address octet defined as a range (e.g., 100..254)
  IPRange = [100, 254]

  # MacsToFind are the MAC addresses (e.g., "24:da:9b:0d:53:8f") of user proxy device(s)
  # to search for on the LAN
  #
  # IMPORTANT: use colon delimiters only, as this is what the 'ip' command expects 
  #
  MacsToFind = ["24:da:9b:0d:53:8f", "f8:cf:c5:d2:bb:9e"]

[Logging]
  # LogLevel sets the log levels for application logging using the following table
  #
  # Note that DEBUG > INFO > FATAL, so DEBUG includes all log levels
  #
  #  0 - OFF, no logging
  #  1 - FATAL, report fatal events
  #  2 - INFO, report informational events
  #  4 - DEBUG, report debugging events
  #
  LogLevel = 2

  # LogDevice determines to what device logging should be set using the following table:
  #
  #  0 - STDOUT (terminal)
  #  1 - log file
  #
  # Ignored if LogLevel == 0
  #
  LogDevice = 0

  # LogFilename is the logging filename
  #
  # Ignored if LogLevel == 0 or LogDevice == 0
  #
  LogFilename = "dms3server.log"

  # LogLocation is the location of logfile (absolute path; must have r/w permissions)
  #
  # Ignored if LogLevel == 0 or LogDevice == 0
  #
  LogLocation = "/var/log/dms3"
